feature/client-settings
cavoke-project/cavoke pull request #112
Opened 2022-04-09 20:27 UTC by MarkTheHopeful

Добавлены настройки клиента:

1. Обновлён экран Settings: Теперь он в едином стиле с остальными рабочими экранами, а так же на нём можно ввести ник и адрес хоста. (Ник пока никуда не используется)
2. Введённые параметры сохраняются (точное место зависит от платформы, Qt обо всём само заботится) между запусками.
3. Введённый адрес хоста используется NetworkManager-ом. При нажатии на кнопку сохранения настроек происходит повторная загрузка по указанному адресу (В случае, если указанное адресом не является, то просто ничего не изменится, просто связи с сервером не будет).
4. Никакой верификации полей нет, увы. Но вроде пока и не особо нужна.

Closes #95

2022-04-09 22:38 UTC, waleko requested changes
в целом кайф, но есть комментарии + бага

2022-04-09 22:38 UTC, waleko commented on client/network_manager.h
> +    QUrl HOST{BASE_HOST};
Крашается при интересных действиях

### Description
При смене хоста не удаляются старые игры

### Steps to reproduce
1. Поставить рабочий хост
1. Зайти в настройки и просто нажать update (можно не менять хоста)
1. Посмотреть список доступных игр. Там будет два раза крестики-нолики.
1. Нажать на вторые. Приложение упадет

2022-04-09 22:38 UTC, waleko commented on client/views/settingsview.cpp
> +    ui->serverAddressInput->setText(host);
не большой специалист ui/ux, но может при установке настроек сразу возвращать назад (переименовать соответственно кнопочку). Потому что не сразу понял, что всё случилось, подумал, что может думает.

2022-04-09 22:40 UTC, MarkTheHopeful commented on client/controllers/cavokeclientcontroller.h
> +    const static inline QUrl BASE_HOST{"https://develop.api.cavoke.wlko.me"};
О, фига, реально, уберу лишний

2022-04-09 22:40 UTC, MarkTheHopeful commented on client/network_manager.h
> +    const static inline QUrl BASE_HOST{"https://develop.api.cavoke.wlko.me"};
Хм, окей, переименую. Вообще он используется только при первом запуске, по хорошему... Но просто тогда уже хз, можно отдельно бахнуть файлик "Важные крутые константы значений по умолчанию"

2022-04-09 22:41 UTC, MarkTheHopeful commented on client/controllers/cavokeclientcontroller.cpp
> +    // Default settings initialization
Там вообще весь этот конструктор надо бы на методы-части разбить...

2022-04-09 22:41 UTC, MarkTheHopeful commented on client/controllers/cavokeclientcontroller.cpp
> +                      settings.value("player/nickname", "Guest"));
Всё ещё можно бахнуть отдельный файлик для констант

2022-04-09 22:42 UTC, MarkTheHopeful commented on client/network_manager.cpp
> +    getGamesList();  // Reload games list. Seems bad
Хм, действительно, похоже

2022-04-09 22:43 UTC, MarkTheHopeful commented on client/network_manager.h
> +    QUrl HOST{BASE_HOST};
О_О
Sounds interesting, похоже всё же придётся очищать список при обновлениях... Ок, исправлю

2022-04-09 22:44 UTC, MarkTheHopeful commented on client/views/settingsview.cpp
> +    ui->serverAddressInput->setText(host);
Хм, можно и назад возвращать. Наверно, хотелось бы какой-нибудь сплеш показать типо "Настройки сохранены"

2022-04-09 22:59 UTC, waleko commented on client/views/settingsview.cpp
> +    ui->serverAddressInput->setText(host);
сплеш имхо заморочно

2022-04-09 23:34 UTC, waleko commented on client/main.cpp
> +    QCoreApplication::setOrganizationDomain("cavoke.alexkovrigin.me");
сделал, чтобы на cavoke.wlko.me показывалась та же старая страница

2022-04-10 20:16 UTC, MarkTheHopeful commented on client/main.cpp
> +    QCoreApplication::setOrganizationDomain("cavoke.alexkovrigin.me");
Было бы неплохо что-нибудь кинуть на cavoke.wlko.me, наверно

2022-04-10 22:10 UTC, waleko commented on client/main.cpp
> +    QCoreApplication::setOrganizationDomain("cavoke.alexkovrigin.me");
> Было бы неплохо что-нибудь кинуть на cavoke.wlko.me, наверно

решил не миррорить сайт, ибо там слишком много не относящейся к делу фигни. постаивл на cavoke.wlko.me наш readme

2022-04-10 22:14 UTC, waleko requested changes
Все претензии к коду кончились!

Но у меня до сих пор падает:

### Steps to reproduce
1. Create Game -> Back
2. Settings -> Update -> Crash

2022-04-10 22:16 UTC, waleko commented
> Все претензии к коду кончились!
> 
> Но у меня до сих пор падает:
> 
> ### Steps to reproduce
> 1. Create Game -> Back
> 2. Settings -> Update -> Crash

Кстати у меня просто Update сразу crash, может это у меня проблемы, хз

2022-04-11 08:17 UTC, MarkTheHopeful commented
А ведь реально падает...

2022-04-11 09:03 UTC, waleko approved these changes

2022-04-11 09:08 UTC, merged