feature/server-host-memorization
cavoke-project/cavoke pull request #138
Opened 2022-05-04 18:17 UTC by MarkTheHopeful

У GameSession теперь есть поле host, в котором лежит UUID текущего хоста -- администратора сессии.

Теперь запустить игру может только хост.

Добавлена функция "передать хоста", с помощью которой хост может сделать другого игрока хостом.

Теперь, когда хост выходит из сессии и, если в сессии ещё остались игроки, то один из них становится новым хостом, а иначе (сессия пуста) сессия удаляется.

Неприятности -- в написанном много потенциальных мест, где может произойти race condition, к сожалению. Стоит посмотреть написанное на этот счёт. Плюс просто проверить, что я нормально склеил скопированные куски чужого кода во что-то работающее...

P.S. Автогенерация перегенерировала, а потом ещё что-то съело/убило CRLF/LF и теперь там что-то другое, возможно, отсюда и изменения. Ну и плюс туда host был добавлен.

Close #132

2022-05-04 20:08 UTC, waleko requested changes
предложил решения атомарности: `transfer` простое, `leave` сложное

2022-05-04 20:08 UTC, waleko commented on server/model/sessions/game_session.cpp
> +    if (!is_player(user_id)) {
например
```sql
constraint sessions_players_session_id_user_id_fk
        foreign key (id, host_id) references players
```

2022-05-04 20:08 UTC, waleko commented on server/controllers/sessions_controller.cpp
> +    if (!session.is_host(user_id.value())) {
атомарность туда же

2022-05-07 13:07 UTC, MarkTheHopeful commented on server/model/sessions/game_session.cpp
> +bool GameSessionAccessObject::is_host(const std::string &user_id) const {
done

2022-05-07 13:08 UTC, MarkTheHopeful commented on server/model/sessions/game_session.cpp
> +                 CompareOperator::NE, session_snapshot.getValueOfHostId()));
Ох, а как такой запрос в сыром виде сделать?

2022-05-07 13:11 UTC, MarkTheHopeful commented on server/model/sessions/game_session.cpp
> +    if (session.getValueOfStatus() != NOT_STARTED) {
Да вроде ничему, просто у нас пока как-то не очень вообще идёт работа с любыми изменениями состава сессии в процессе самой игры

2022-05-07 13:12 UTC, MarkTheHopeful commented on server/model/sessions/game_session.cpp
> +void GameSessionAccessObject::transfer_host_to(const std::string &user_id) {
done

2022-05-11 08:46 UTC, MarkTheHopeful commented on server/controllers/sessions_controller.cpp
> +    if (!session.is_host(user_id.value())) {
Пусть пока в issue лежит

2022-05-11 09:03 UTC, waleko commented on server/controllers/sessions_controller.cpp
> +        user_id.value());  // what could possibly go wrong?
ой может лучше вынести запросы к db в game_session.cpp, чтобы единообразно в контроллерах только обращения к gamesessionAO

2022-05-11 09:03 UTC, waleko commented on server/controllers/sessions_controller.cpp
> +        "select transfer_to_available($1::uuid, $2::uuid);", session_id,
может раз такое пошло, переименовать функцию во что-то вида `leave_session(...)`, чтобы бвло понятно, а то там игрока то тоже удаляют

2022-05-11 09:16 UTC, MarkTheHopeful commented on server/model/sessions/sessions_storage.cpp
> +        auto transaction = drogon::app().getDbClient()->newTransaction();
Так, а как тогда тут закоммитить изменение хоста без транзакции? Туплю

2022-05-11 09:16 UTC, MarkTheHopeful commented on server/controllers/sessions_controller.cpp
> +        "select transfer_to_available($1::uuid, $2::uuid);", session_id,
done

2022-05-11 12:24 UTC, MarkTheHopeful commented on server/model/sessions/sessions_storage.cpp
> +        auto transaction = drogon::app().getDbClient()->newTransaction();
Ок, прикрепилось к одной из штук, done, i guess

2022-05-11 13:34 UTC, waleko approved these changes

2022-05-11 13:40 UTC, merged