Codenames
cavoke-project/cavoke pull request #139
Opened 2022-05-04 22:25 UTC by petrtsv

Доделал Codenames. 

Есть логика и интерфейс, для сборки интерфейса в архив есть скрипт build.sh 

Игра поддерживает разные словари, я подготовил русский и английский, они лежат в папке assets, ее надо класть рядом с логикой на сервере. Для поддержки ассетов немного поменял на сервере код запуска логики

2022-05-07 12:53 UTC, MarkTheHopeful reviewed
Сейчас пойду тестировать...

2022-05-07 12:53 UTC, MarkTheHopeful commented on .gitignore
> +/games/codenames/client/client.zip
Мб откомментировать, что это и зачем, ну или просто поставить на всё вида *client.zip

2022-05-07 12:53 UTC, MarkTheHopeful commented on games/CMakeLists.txt
> +
Стоп, а как оно раньше без этого жило?

2022-05-07 12:53 UTC, MarkTheHopeful commented on games/codenames/config.json
> +  "description": "Our second cavoke game!",
Хотелось бы описание игры, чтобы потом к презентации не менять.

2022-05-07 12:53 UTC, MarkTheHopeful commented on games/codenames/server/assets/wordlists/ru.txt
> +рука
Этот список взят откуда-то конкретно, или случайносоставлен?

2022-05-07 12:53 UTC, MarkTheHopeful commented on server/model/games/game.h
> +public:
Почему они потребовались публичными?

2022-05-07 12:53 UTC, MarkTheHopeful commented on server/model/logic/game_logic_manager.cpp
> +    bp::child c(game.LOGIC_FILE, bp::start_dir(game.directory),
Чем отличается LOGIC_FILE от logic_file?

2022-05-07 13:00 UTC, MarkTheHopeful commented
А нет, пока deps от Саши не вмёржится, протестить не смогу, похоже

2022-05-07 16:54 UTC, waleko requested changes
:fire:

пару вопросов и предложений по коду

баг про чтение из `boost::process`, который обсуждали.

под убунтой (в docker-compose) всё работает

2022-05-11 18:04 UTC, MarkTheHopeful commented
![2022-05-11-210050_1920x1080_scrot](https://user-images.githubusercontent.com/38182188/167916586-b1639a8d-12a8-4411-9af9-b5bb7676ce8a.png)

Мелочь, но забавная. А ещё нельзя дать подсказку с числом "0", хотя согласно правилам так можно и это даёт бесконечность попыток

2022-05-11 18:35 UTC, petrtsv commented
> ![2022-05-11-210050_1920x1080_scrot](https://user-images.githubusercontent.com/38182188/167916586-b1639a8d-12a8-4411-9af9-b5bb7676ce8a.png)
> 
> Мелочь, но забавная. А ещё нельзя дать подсказку с числом "0", хотя согласно правилам так можно и это даёт бесконечность попыток

Ну, тут https://www.mosigra.ru/image/data/mosigra.product.other/544/093/Codenames_rules.pdf написано, что это доп правило))

2022-05-11 18:59 UTC, waleko approved these changes

2022-05-11 22:53 UTC, MarkTheHopeful approved these changes
Вроде всё круто! Так, упустил момент, а где задаётся директория, в которой сервер будет искать условные assets?

2022-05-11 23:59 UTC, merged