Feature/basic interface
cavoke-project/cavoke pull request #6
Opened 2022-02-13 17:20 UTC by MarkTheHopeful

Добавил базу для интерфейса -- стартовый экран с кнопками. Раскидал файлы по директориям. Добавил темлейты для `StartGameView`, `JoinGameView`, `SettingsView`. Пофиксил название проекта в `CMakeLists.txt`. Во, вроде всё

2022-02-13 19:58 UTC, waleko requested changes

2022-02-13 19:58 UTC, waleko commented on client/controllers/cavokeclientcontroller.cpp
> +    connect(&startView, SIGNAL(shownSettingsView()), this, SLOT(showSettingsView()));
Точно ли нужна сложная система одновременных открытий/закрытий окон? Не получится просто поверх `StartView` открывать новые окна?

Возможно, что `StartView` будет довольно сложным, там может быть будет "магазин" доступных игр, не знаю, может, его можно держать открытым, а из него запускать маленькие диалоги.

2022-02-13 19:58 UTC, waleko commented on client/README.md
> +   - [x] Подгрузка QML по переданному абсолютному пути (см. [QFileDialog](https://doc.qt.io/qt-5/qfiledialog.html) и [пример](https://github.com/waleko/PictureCrypt/blob/master/src/app/testWindowView
Вероятно нечаянная замена

2022-02-13 19:58 UTC, waleko commented on client/controllers/cavokeclientcontroller.cpp
> +void CavokeClientController::exitApplication() {
по закрытию одного окна программа завершается целиком, это приятно

2022-02-13 19:58 UTC, waleko commented on client/main.cpp
> +int main(int argc, char *argv[]) {
если пошел разговор о code style, возможно стоит задуматься о `clangformat` #16

2022-02-13 22:38 UTC, waleko commented
можно начать делать какие-то запросы из модели к серверу. есть mock: https://15278206-a4fd-4741-8bc8-9d085f3924c4.mock.pstmn.io

2022-02-18 17:02 UTC, MarkTheHopeful commented on client/controllers/cavokeclientcontroller.cpp
> +    connect(&startView, SIGNAL(shownSettingsView()), this, SLOT(showSettingsView()));
Не совсем понял, в каком виде предполагается запускать диалоги. Дополнительные диалоговые окна поверх основного? Или диалоговое окно может сменять исходное, не закрывая его? Плюс не уверен, что остальные окна будут маленькими.

2022-02-18 17:02 UTC, MarkTheHopeful commented on client/README.md
> +   - [x] Подгрузка QML по переданному абсолютному пути (см. [QFileDialog](https://doc.qt.io/qt-5/qfiledialog.html) и [пример](https://github.com/waleko/PictureCrypt/blob/master/src/app/testWindowView
Окей, исправлю

2022-02-18 17:03 UTC, MarkTheHopeful commented on client/controllers/cavokeclientcontroller.cpp
> +void CavokeClientController::exitApplication() {
Не совсем понял, о чём комментарий

2022-02-18 17:22 UTC, waleko commented on client/controllers/cavokeclientcontroller.cpp
> +    connect(&startView, SIGNAL(shownSettingsView()), this, SLOT(showSettingsView()));
Я думал об окнах поверх других окон. А какие окна будут немаленькими? Не настаиваю на своём.

2022-02-18 17:25 UTC, waleko commented
> > можно начать делать какие-то запросы из модели к серверу. есть mock: https://6a49a943-ed5b-4809-8469-f2fc2fcd3c0a.mock.pstmn.io
> 
> А оно точно работает? Если да, то как?

Да... Там каждый раз, когда что-нибудь меняешь, оно перестаёт работать с настроенными утилитами...

Если всё-таки хочется, вот ссылка, которая пока что работает: https://82c739f6-9577-4b5c-b4c9-2cc92e0c1474.mock.pstmn.io

Но в целом наверное проще поднимать что-то похожее на локалке (хоть в том же постмане)

2022-02-19 13:55 UTC, MarkTheHopeful commented on client/controllers/cavokeclientcontroller.cpp
> +    connect(&startView, SIGNAL(shownSettingsView()), this, SLOT(showSettingsView()));
Вроде обсудили, решили пока так оставить

2022-02-19 14:18 UTC, waleko approved these changes

2022-02-19 15:46 UTC, merged